-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgRf8ec6JlhV4pSrQ6
AXQUJE0dDpKJJypI+8CuReV2+XegCgYIKoZIzj0DAQehRANCAATLIrQdILcZTbeP
rJ2IIXth1S16j+Ct4lOBcpiU0+Q6+IPdGDmwcfKRhUgHdFhCuZmi5smPJT8Xw5JO
TdhU/9ah
-----END PRIVATE KEY-----